name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-go@v2
      #with:
      #  go-version: '1.17'
    - name: Checks
      run: |
        go version
        go vet .
        go test ./... -v
        env
    - name: Build
      run: go build .
    - name: Uncommit
      run: |
        cd "${GITHUB_WORKSPACE}"
        git branch ${GITHUB_REF}
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git reset --hard HEAD~1
        git push --force
