name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Setup
      uses: actions/setup-go@v2
      #with:
      #  go-version: '1.17'
    - name: Checks
      run: |
        awk --version
        gh version
        jq --version
        gh release view --json tagName
        echo "-----------"
        ver=$(($(gh release view --json tagName|jq .tagName -r|awk -F. '{print $3}')+1))
        echo "Next version ($ver)"
        echo "-----------"
        env
    # - name: Build
    #   run: go build .
    # - name: Uncommit
    #   if: failure()
    #   run: |
    #     echo "${GITHUB_WORKSPACE} : ${GITHUB_REF}"
    #     cd ${GITHUB_WORKSPACE}
    #     git status
    #     git branch ${GITHUB_REF}
    #     git config --global user.name "github-actions[bot]"
    #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
    #     git reset --hard HEAD~1
    #     git push --force
