name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-go@v2
      #with:
      #  go-version: '1.17'
    - name: Checks
      run: |
        go version
        go vet .
        go test ./... -v
        env
    - name: Build
      run: go build .
