name: Deploy

on: 
  release:
    types: [published,deleted]
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy
      env:
        TEMP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh auth login --with-token <<<"$TEMP_TOKEN"
        ver=$(gh release view --json tagName|jq .tagName -r|awk -F. '{print $3}')
        echo "Deploy v0.0.$ver"
