name: Deploy

on: 
  release:
    types: [published,deleted]
    tags:
      - 'v*'
  workflow_run:
    workflows: ["Tag for release"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - name: Deploy
      env:
        TEMP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "### START"
        gh auth login --with-token <<<"$TEMP_TOKEN"
        echo "### POST gh AUTH"
        ver=$(gh release view --json tagName|jq .tagName -r|awk -F. '{print $3}')
        echo "### POST gh release"
        echo "Deploy v0.0.$ver"
        git log -n5
        echo "### POST git log"
        git checkout "v0.0.$ver"
        echo "### POST git checkout"
        cat code.txt
