name: Tag for release

on:
  workflow_dispatch:
    inputs:
      run:
        description: Press run
        default: main
        requiored: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Setup
      uses: actions/setup-go@v2
    - name: Checks
      env:
        TEMP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh auth login --with-token <<<"$TEMP_TOKEN"
        gh release view --json tagName
        ver=$(($(gh release view --json tagName|jq .tagName -r|awk -F. '{print $3}')+1))
        gh release create "v0.0.$ver" --generate-notes
