name: Tag for release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # - name: Setup
    #   uses: actions/setup-go@v2
    - name: Create release tag
      env:
        TEMP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh auth login --with-token <<<"$TEMP_TOKEN"
        gh release view --json tagName
        ver=$(($(gh release view --json tagName|jq .tagName -r|awk -F. '{print $3}')+1))
        gh release create "v0.0.$ver" --generate-notes
